### ISSUE TITLE
Make functional with GPS AudioMoth files

### ISSUE THREAD

**Issue by lmc150** [sammlapp/picopy#7]
In addition to CONFIG.TXT and .WAV files, GPS AudioMoths also create .PPS files with firmware v 1.0.8, and previous versions created .RMC, .CNT, etc. Currently, such files are ignored by the Swallows.

The Swallows should be more lenient with what file types they will transfer. The solution is probably to only ignore small .WAV files as it seems the GPS AudioMoths have changed the file types they write between firmwares.

**Comment by sammlapp** [comment]
now includes all files except a few ignored hidden types and .wav/.WAV under 100kb
